openapi: 3.0.3 
info: 
  title: "Notebook API" 
  version: "0.0.1" 
paths: 
  /api/contacts: 
    get: 
      summary: Получение всех контактов через пагинацию
      operationId: GetContacts 
      parameters: 
        - name: pageToken 
          in: query
          required: false
          schema:
            type: string
            nullable: true
          description: Paging token (opaque string, may be JSON-serialized internally)
          example: null
        - name: pageSize 
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 1000
          description: Paging 
          example: 100
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContacts'
              example:
                contacts:
                  - name: "Егор Щербинин"
                    number: "89992226622"
                    email: "sherb@mail.ru"
                    age: 22
                  - name: "Никита Дресвянников"
                    number: "87772223344"
                    email: "dresv234@yamdex.ru"
                    age: 22
                pageToken: "dsjkfs2h3kj32jd2h3"
        '400':
          description: Validation error
    post:
      summary: Создание контакта
      operationId: PostContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContactRequest'
            example:
              name: "Иван Петров"
              number: "+79991112233"
              age: 25
              city: "Москва"
              description: "Коллега"
      responses:
        '201':
          description: Created
  /api/contact/{id}:
    get:
      summary: Получение конкретного контакта
      operationId: GetContact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 33
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContact'
              example:
                name: "Егор Щербинин"
                number: "89992226622"
                email: "sherb@mail.ru"
                age: 22  
        '404':
          description: Not Found
    put:
      summary: Полное изменение контакта
      operationId: PutContact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 33
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContactRequest'
            example:
              name: "Иван Петров"
              number: "+79991112233"
              age: 25
              city: "Москва"
              description: "Коллега"
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    patch:
      summary: Изменение контакта
      operationId: PatchContact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 33
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContactRequest'
            example:
              age: 25
              city: "Москва"
components:
  schemas:
    GetContacts:
      type: object
      required: [contacts]
      properties:
        contacts:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/GetContact'
        pageToken:
          type: string
          nullable: true
    GetContact:
      type: object
      required: [name, number, age]
      properties:
        name:
          type: string
          nullable: false
          example: "Alexander"
        number:
          type: string
          nullable: false
          example: "82223334455"
          minLength: 11
          maxLength: 11 
        age:
          type: integer
          minimum: 0
          maximum: 150
          nullable: false
          example: 11
        email:
          type: string
          format: email
          nullable: false
          example: "Alexander22@mail.ru"
        city:
          type: string 
          nullable: false
          example: "Moscow"
        description:
          type: string
          nullable: true
          example: "Лучший друг"
    CreateContactRequest:
      type: object
      required: [name, number, age]
      properties:
        name:
          type: string
          nullable: false
          example: "Alexander"
        number:
          type: string
          nullable: false
          example: "82223334455"
          minLength: 11
          maxLength: 11 
        age:
          type: integer
          minimum: 0
          maximum: 150
          nullable: false
          example: 11
        email:
          type: string
          format: email
          nullable: false
          example: "Alexander22@mail.ru"
        city:
          type: string 
          nullable: false
          example: "Moscow"
        description:
          type: string
          nullable: true
          example: "Лучший друг"
    UpdateContactRequest:
      type: object
      properties:
        name:
          type: string
          nullable: false
          example: "Alexander"
        number:
          type: string
          nullable: false
          example: "82223334455"
          minLength: 11
          maxLength: 11 
        age:
          type: integer
          minimum: 0
          maximum: 150
          nullable: false
          example: 11
        email:
          type: string
          format: email
          nullable: false
          example: "Alexander22@mail.ru"
        city:
          type: string 
          nullable: false
          example: "Moscow"
        description:
          type: string
          nullable: true
          example: "Лучший друг"